# Generated by Django 2.0.6 on 2018-06-25 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('feedback', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64)),
                ('song_name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('queued', models.BooleanField(default=False)),
                ('artwork', models.CharField(blank=True, max_length=256)),
                ('duration_ms', models.IntegerField(default=0)),
                ('dj_pick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('time', models.FloatField()),
                ('running', models.BooleanField(default=False)),
                ('last_play_time', models.FloatField(default=0)),
                ('progress_ms', models.IntegerField(default=0)),
                ('last_locked_in_id', models.CharField(blank=True, max_length=256, null=True)),
                ('playlist_index', models.PositiveIntegerField(default=0)),
                ('playing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj.Song')),
            ],
        ),
    ]
