# Generated by Django 2.0.6 on 2018-07-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyinfo',
            name='client_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='spotifyinfo',
            name='client_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='spotifyinfo',
            name='default_playlist',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='spotifyinfo',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
